version: "3"
services:
  apollo:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: spirit-apollo
    container_name: spirit-apollo-dev
    env_file: .env
    environment:
      NODE_ENV: development
      PG_USERNAME: ${DEV_PG_USERNAME}
      PG_PASSWORD: ${DEV_PG_PASSWORD}
      PG_HOSTNAME: db
      PG_PORT: 5432
      PG_DB: ${DEV_PG_DB}
    ports:
    - 4000:4000
    - 9229:9229
    volumes:
      - ./:/usr/src/apollo
      - /node_modules
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    container_name: spirit-db-dev
    env_file: .env
    environment:
      POSTGRES_USER: ${DEV_PG_USERNAME}
      POSTGRES_PASSWORD: ${DEV_PG_PASSWORD}
      POSTGRES_DB: ${DEV_PG_DB}
    volumes:  
      - dbdata:/var/lib/postgresql
    networks:
      - app-network

  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "8090:80"
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  pgadmin:
  node_modules: 