version: "3"
services:
  apollo:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      SECRET: 'supersecretword'
      MONGO_HOST: 'mongodb://mongo/app'
      PORT: 4000
    ports:
    - "4000:4000"
    volumes:
      - ./:/usr/src/apollo
      - /node_modules