image: tmaier/docker-compose:latest

services:
  - name: docker:dind
    alias: docker

stages:
  - test
  - build
  - deploy
  - post-deploy

apollo-deploy-prod:
  stage: deploy
  tags:
    - apollo
    - prod
  variables:
    PG_DB: $PROD_PG_DB
    PG_HOSTNAME: $PROD_PG_HOSTNAME
    PG_PASSWORD: $PROD_PG_PASSWORD
    PG_PORT: $PROD_PG_PORT
    PG_USERNAME: $PROD_PG_USERNAME
    PGADMIN_EMAIL: $PROD_PGADMIN_EMAIL
    PGADMIN_PASSWORD: $PROD_PGADMIN_PASSWORD
    PGADMIN_PORT: $PROD_PGADMIN_PORT
  script:
    - chmod +x ./setup.env.sh
    - chmod +x ./packages/apollo/start.sh
    - ./setup.env.sh
    - docker-compose -f docker-compose.apollo.prod.yml up -d --build
  only:
    - master

db-setup-prod:
  stage: post-deploy
  when: on_success
  needs:
    - apollo-deploy-prod
  tags:
    - apollo
    - prod
  script:
    - docker exec spirit-apollo-prod chmod +x ./setup.db.sh
    - docker exec spirit-apollo-prod ./setup.db.sh
  only:
    - master

admin-deploy-prod:
  stage: deploy
  tags:
    - admin
    - prod
  variables:
    APOLLO_URI: $APOLLO_SERVER_URL
  script:
    - echo "APOLLO_URI=$APOLLO_URI" >> ./packages/admin/.env
    - cat ./packages/admin/.env
    - docker-compose -f docker-compose.admin.prod.yml build
    - docker-compose -f docker-compose.admin.prod.yml up -d
  only:
    - master
