stages:
  - apollo-test
  - apollo-build
  - apollo-deploy

apollo-test:
  stage: apollo-test
  tags:
    - apollo
  script:
    - echo "Test is good!"

apollo-build:
  stage: apollo-build
  tags:
    - apollo
  script:
    - echo "Apollo Is Builded"

apollo-deploy-uat:
  stage: apollo-deploy
  tags:
    - apollo
    - uat
  script:
    - echo "Deploy on UAT is finished!"
  only:
    - master

apollo-deploy-prod:
  stage: apollo-deploy
  when: manual
  tags:
    - apollo
    - prod
  script:
    - echo "Deploy on PROD is finished!"
  only:
    - master
