version: "3"
services:
  admin:
    build:
      context: ./packages/admin/
      dockerfile: Dockerfile.dev
    image: spirit-admin
    container_name: spirit-admin-dev
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
    - 5000:8000
    volumes:
      - .:/usr/src/app
      - admin_node_modules:/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  admin_node_modules: 