version: "3"
services:
  admin:
    build:
      context: ./packages/
      dockerfile: admin/Dockerfile.prod
    image: spirit-admin
    restart: unless-stopped
    container_name: spirit-admin-prod
    ports:
      - 80:80
      - 443:443
    environment:
      NODE_ENV: production
