version: "3"
services:
  admin:
    build:
      context: ./packages/admin/
      dockerfile: Dockerfile.dev
    image: spirit-admin
    container_name: spirit-admin-dev
    environment:
      NODE_ENV: development
    ports:
    - 5000:8000
    volumes:
      - .:/usr/src/app
      - admin_node_modules:/node_modules

volumes:
  admin_node_modules: 