version: "3"
services:
  portal:
    build:
      context: ./packages/portal/
      dockerfile: Dockerfile.dev
    image: spirit-portal
    container_name: spirit-portal-dev
    environment:
      NODE_ENV: development
    ports:
    - 3000:3000
    volumes:
      - .:/usr/src/app
      - portal_node_modules:/node_modules

volumes:
  portal_node_modules: 