version: "3"
services:
  apollo:
    build:
      context: ./packages/apollo/
      dockerfile: Dockerfile.prod
    image: spirit-apollo
    container_name: spirit-apollo-prod
    env_file: .env
    environment:
      NODE_ENV: production
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOSTNAME: ${PG_HOSTNAME}
      PG_PORT: ${PG_PORT}
      PG_DB: ${PG_DB}
    ports:
    - 4000:4000
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    container_name: spirit-db-prod
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - ${PG_PORT}:5432
    volumes:  
      - dbdata:/var/lib/postgresql
    networks:
      - app-network

  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge