// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ItemImage': string;
  'ItemImageWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
