// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'headerSearch': string;
  'input': string;
  'show': string;
}
export const cssExports: CssExports;
export default cssExports;
