extend type Query {
  companies: [Company!]
  company(id: ID!): Company
}

extend type Mutation {
  createCompany(name: String!, slug: String!, productCategoryId: ID!): Company!
}

type Company {
  id: ID!
  name: String!
  slug: String!
  productCategory: ProductCategory!
  products: [Product]!
} 