// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'isHorizontal': string;
  'isLarge': string;
  'isMiddle': string;
  'isVertical': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
