// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'content': string;
  'desc': string;
  'exception': string;
  'imgBlock': string;
  'imgEle': string;
}
export const cssExports: CssExports;
export default cssExports;
