extend type Query {
  procurements: [Procurement]!
  procurement(id: ID!): Procurement
}

extend type Mutation {
  createProcurement(input: ProcurementInput!): Procurement!
  addProductProcurement(input: ProductProcurementInput): Procurement!
}

input ProductProcurementInput {
  productId: ID!
  procurementId: ID!
  count: Int!
  costs: Float!
}

input ProcurementInput {
  nextStatusDate: String
  deliveryCost: Float
}

type ProductProcurement {
  count: Int!
  costs: Float!
  procurement: Procurement!
  product: Product!
}

type Procurement {
  id: ID!
  status: String!
  nextStatusDate: String
  deliveryCost: Float
  productProcurements: [ProductProcurement]!
} 